# Generated by Django 5.2.14 on 2026-05-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_customer_email_remove_customer_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "permissions": [
                    (
                        "send_private_email",
                        "Can send private email to user by the button",
                    )
                ]
            },
        ),
    ]
